# Data Science Books Dataset Cleaning  
### [Amazon Data Science Books Dataset from Kaggle](https://www.kaggle.com/datasets/die9origephit/amazon-data-science-books)  
### Work done by: [@chusk2](https://twitter.com/chusk2)  
### Github repository: [data_cleaning](https://github.com/chusk2/data_cleaning)

## Import python libraries

In [1]:
import pandas as pd
import numpy as np

## Import raw data

In [2]:
data = pd.read_csv('data_science_books.csv')

## First overlook

In [3]:
data.head()

title  \
0  Data Analysis Using R (Low Priced Edition): A ...   
1  Head First Data Analysis: A learner's guide to...   
2  Guerrilla Data Analysis Using Microsoft Excel:...   
3  Python for Data Analysis: Data Wrangling with ...   
4  Excel Data Analysis For Dummies (For Dummies (...   

                               author  price price (including used books)  \
0                 [ Dr Dhaval Maheta]   6.75                         6.75   
1                                 NaN  33.72               21.49 - 33.72    
2  [ Oz du Soleil,  and , Bill Jelen]  32.07                        32.07   
3                 [ William McKinney]  53.99                        53.99   
4                   [ Paul McFedries]  24.49                        24.49   

  pages  avg_reviews n_reviews star5 star4 star3 star2 star1  \
0   500          4.4        23   55%   39%    6%   NaN   NaN   
1   484          4.3       124   61%   20%    9%    4%    6%   
2   274          4.7        10   87%   13%   NaN   NaN   NaN   
3   547          4.6     1,686   75%   16%    5%    2%    2%   
4   368          3.9        12   52%   17%   10%   10%   10%   

                  dimensions       weight language  \
0     8.5 x 1.01 x 11 inches  2.53 pounds  English   
1     8 x 0.98 x 9.25 inches  1.96 pounds  English   
2  8.25 x 0.6 x 10.75 inches   1.4 pounds  English   
3     7 x 1.11 x 9.19 inches  1.47 pounds  English   
4  7.38 x 0.83 x 9.25 inches   1.3 pounds  English   

                                           publisher         ISBN_13  \
0     Notion Press Media Pvt Ltd (November 22, 2021)  978-1685549596   
1      O'Reilly Media; 1st edition (August 18, 2009)  978-0596153939   
2  Holy Macro! Books; Third edition (August 1, 2022)  978-1615470747   
3    O'Reilly Media; 2nd edition (November 14, 2017)  978-1491957660   
4        For Dummies; 5th edition (February 3, 2022)  978-1119844426   

                                                link  \
0  /Data-Analysis-Using-Low-Priced/dp/1685549594/...   
1  /Head-First-Data-Analysis-statistics/dp/059615...   
2  /Guerrilla-Analysis-Using-Microsoft-Excel/dp/1...   
3  /Python-Data-Analysis-Wrangling-IPython/dp/149...   
4  /Excel-Data-Analysis-Dummies-Computer/dp/11198...   

                                       complete_link  
0  https://www.amazon.com/Data-Analysis-Using-Low...  
1  https://www.amazon.com/Head-First-Data-Analysi...  
2  https://www.amazon.com/Guerrilla-Analysis-Usin...  
3  https://www.amazon.com/Python-Data-Analysis-Wr...  
4  https://www.amazon.com/Excel-Data-Analysis-Dum...

In [4]:
data.columns

Index(['title', 'author', 'price', 'price (including used books)', 'pages',
       'avg_reviews', 'n_reviews', 'star5', 'star4', 'star3', 'star2', 'star1',
       'dimensions', 'weight', 'language', 'publisher', 'ISBN_13', 'link',
       'complete_link'],
      dtype='object')

# Dataset cleaning process

## Subset of the raw data

In [5]:
df = data['title, author, price, pages, language, publisher, ISBN_13, complete_link'.split(', ')]

In [6]:
df.columns

Index(['title', 'author', 'price', 'pages', 'language', 'publisher', 'ISBN_13',
       'complete_link'],
      dtype='object')

## Clean `author`

In [7]:
df.author.isna().count()

830

In [8]:
def clean_author(value):
	if value == value:
		return value.lstrip('[ ').rstrip(']').replace(',  and ,', ' and')
	else:
		return value

In [9]:
df.author = df.author.apply(clean_author)

C:\Users\code\AppData\Local\Temp\ipykernel_4536\4174911401.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.author = df.author.apply(clean_author)


In [10]:
df.sample(10)

title  \
784  The Handbook of Data Science and AI: Generate ...   
65             CompTIA Data+ Study Guide: Exam DA0-001   
543  Web Scraping with Python: Collecting More Data...   
781    Data Science in Chemistry (De Gruyter Textbook)   
655  The Self-Taught Computer Scientist: The Beginn...   
291  Learning R: A Step-by-Step Function Guide to D...   
233  The Data Revolution: A Critical Analysis of Bi...   
149       Introduction to Statistics and Data Analysis   
47   Kafka: The Definitive Guide: Real-Time Data an...   
596  Applied Geospatial Data Science with Python: T...   

                                      author  price                     pages  \
784  Stefan Papp, Wolfgang Weidinger, et al.  42.49                       576   
65             Mike Chapple and Sharif Nijim  34.49                       368   
543                            Ryan Mitchell  33.49  Parse complicated HTML     
781                       Thorsten Gressling  52.64                       330   
655                             Cory Althoff  19.49                       224   
291                           Richard Cotton  40.99                       396   
233                              Rob Kitchin  42.00                       376   
149           Roxy Peck, Chris Olsen, et al.  15.10                       944   
47         Gwen Shapira, Todd Palino, et al.  31.99                       488   
596                             David Jordan  54.51                       308   

    language                                          publisher  \
784  English               Hanser Publications (April 28, 2022)   
65   English                Sybex; 1st edition (March 25, 2022)   
543  English          O'Reilly Media; 2nd edition (May 8, 2018)   
781  English                     De Gruyter (November 23, 2020)   
655  English               Wiley; 1st edition (October 1, 2021)   
291  English     O'Reilly Media; 1st edition (October 22, 2013)   
233  English  SAGE Publications Ltd; Second edition (May 31,...   
149  English         Brooks Cole; 5th edition (January 1, 2015)   
47   English    O'Reilly Media; 2nd edition (November 30, 2021)   
596  English  Packt Publishing - ebooks Account (January 10,...   

                 ISBN_13                                      complete_link  
784       978-1569908860  https://www.amazon.com/Handbook-Data-Science-A...  
65        978-1119845256  https://www.amazon.com/CompTIA-Data-Study-Guid...  
543       978-1491985571  https://www.amazon.com/Web-Scraping-Python-Col...  
781       978-3110629392  https://www.amazon.com/Data-Science-Chemistry-...  
655       978-1119724414  https://www.amazon.com/Self-Taught-Computer-Sc...  
291       978-1449357108  https://www.amazon.com/Learning-Step-Step-Func...  
233  The Data Revolution  https://www.amazon.com/Data-Revolution-Critica...  
149       978-1305267244  https://www.amazon.com/Introduction-Statistics...  
47                        https://www.amazon.com/Kafka-Definitive-Real-T...  
596       978-1803238128  https://www.amazon.com/Applied-Geospatial-Data...

## Clean `pages`

There's an error when trying to convert prices to float:  
`ValueError: could not convert string to float: 'Explores all feature...`  
Some values content comments, so I need to clean the price columns first.

In [11]:
#df.pages.astype(float)

I will figure out what's the maximum lenght of the figures in pages column. I will try to convert to float those values of a maximum length. If it raises an error, it means there are values that are strings. In that case, I try using a shorter length for figures.

Length 5 raises an error, but maximum length of pages figure of 4 doesn't.

In [12]:
#df.pages[df.pages.str.len() <=5].astype(float)

In [13]:
df.pages[df.pages.str.len() <=4].astype(float)

0      500.0
1      484.0
2      274.0
3      547.0
4      368.0
       ...  
822    165.0
824    280.0
825    208.0
826    573.0
827    288.0
Name: pages, Length: 736, dtype: float64

Now I know that values longer than 4 are comments. Shorter values correspond to pages number, so there won't be a comment (use NaN). With this information I create a column with comments.

In [14]:
df['comments'] = np.where(df.pages.str.len() >= 5, df.pages, np.nan)

C:\Users\code\AppData\Local\Temp\ipykernel_4536\3878540880.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['comments'] = np.where(df.pages.str.len() >= 5, df.pages, np.nan)


Now let's finally clean the pages column.

In [15]:
df.pages = np.where(df.pages.str.len() <= 4, df.pages, np.nan).astype(float)

C:\Users\code\AppData\Local\Temp\ipykernel_4536\108972310.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.pages = np.where(df.pages.str.len() <= 4, df.pages, np.nan).astype(float)


In [16]:
df.sample(5)

title  \
698  Responsible Data Science: Transparency and Fai...   
660  Democracy's Data: The Hidden Stories in the U....   
500  The Python Bible Volume 5: Python For Finance ...   
245  The Dropout Multi-Millionaire: 37 Business Les...   
271              Excel Formulas (Quick Study Computer)   

                               author  price  pages language  \
698  Peter C. Bruce and Grant Fleming  19.89  304.0  English   
660                          Dan Bouk  25.49  384.0  English   
500                               NaN   7.99   58.0  English   
245                       Brian  WIll   0.99  162.0  English   
271                    Inc. BarCharts   5.95    6.0  English   

                                             publisher         ISBN_13  \
698                  Wiley; 1st edition (May 11, 2021)              59   
660                              MCD (August 23, 2022)  978-0374602543   
500          Independently published (August 14, 2019)  978-1686407376   
245         Bookmark Publishing House (April 30, 2021)             NaN   
271  QuickStudy; Lam Rfc Cr edition (December 31, 2...  978-1423221692   

                                         complete_link comments  
698  https://www.amazon.com/Responsible-Data-Scienc...      NaN  
660  https://www.amazon.com/Democracys-Data-Hidden-...      NaN  
500  https://www.amazon.com/Python-Bible-Finance-An...      NaN  
245  https://www.amazon.com/Dropout-Multi-Millionai...      NaN  
271  https://www.amazon.com/Excel-Formulas-Quick-St...      NaN

## Clean `language`

In [17]:
df.language.unique()

array(['English', nan, 'Spanish',
       'Unqualified, Japanese (Dolby Digital 2.0 Mono), English (Dolby Digital 5.1), English (Dolby Digital 2.0 Mono)',
       'you will discover all you need ',
       '• How to make better business decisions using ',
       'Concepts are presented in a "to-the-point" style to cater to the busy individual. With this book, you can learn Python in just one day and start coding immediately. ',
       'standard library',
       'This Python programming guide assumes certain level of programming knowledge. It is not a beginner textbook.',
       'Scroll to the top of the page and click the ',
       'English (Dolby Digital 2.0 Mono)',
       'English (DTS-HD Master Audio 5.1), French (DTS-HD 2.0)',
       '"Brilliant."'], dtype=object)

Some values have `English` or `Spanish` as language values. Some others have languages with other comments. Other values are just comments. This needs a more deep cleaning than previous columns.

`language` values that don't have English, Spanish, Japanese or French, will be considered as comments.

Multiple conditions to check:

In [18]:
contains_english = df.language.str.contains('English')
contains_spanish = df.language.str.contains('Spanish')
contains_japanese = df.language.str.contains('Japanese')
contains_french = df.language.str.contains('French')

Extract all the values that don't contain information about language.

In [19]:
not_language_info = ~(contains_english | contains_spanish | contains_japanese | contains_french | df.language.isnull() )

In [20]:
df.language[not_language_info]

54                       you will discover all you need 
290       • How to make better business decisions using 
381    Concepts are presented in a "to-the-point" sty...
382                                     standard library
476    This Python programming guide assumes certain ...
492         Scroll to the top of the page and click the 
633                                         "Brilliant."
Name: language, dtype: object

I will store the indexes of these rows, which do not contain some language information.

In [21]:
not_lang_indexes = df.language[not_language_info].index

In [22]:
not_lang_indexes

Int64Index([54, 290, 381, 382, 476, 492, 633], dtype='int64')

Now I will create a function to add these comments to the comments column

Check if these rows have already a comment

In [23]:
df.loc[not_lang_indexes].comments

54       NaN
290      NaN
381      NaN
382    1,000
476      NaN
492      NaN
633      NaN
Name: comments, dtype: object

I have just discovered that row 382 had a valid number of pages:  1000 pages. I sent his page number to comments. I will fix this before going further.

In [24]:
df.loc[382, ['pages']] = 1000
df.loc[382, ['comments']] = np.nan

In [25]:
df.iloc[382]

title            Python 3: The Comprehensive Guide to Hands-On ...
author                           Johannes Ernesti and Peter Kaiser
price                                                        55.48
pages                                                       1000.0
language                                          standard library
publisher        Rheinwerk Computing; First edition (September ...
ISBN_13                                             978-1493223022
complete_link    https://www.amazon.com/gp/slredirect/picassoRe...
comments                                                       NaN
Name: 382, dtype: object

In [26]:
df.loc[not_lang_indexes].comments

54     NaN
290    NaN
381    NaN
382    NaN
476    NaN
492    NaN
633    NaN
Name: comments, dtype: object

Their comments values are NaN, so I will replace the with their values in column `language`

In [27]:
df.loc[not_lang_indexes].comments = df.loc[not_lang_indexes].language

Remove the comments from the `language` column:

In [28]:
df.loc[not_lang_indexes, ['language']] = np.nan

Now let's process the rest of the language values.

In [29]:
df.language.unique()

array(['English', nan, 'Spanish',
       'Unqualified, Japanese (Dolby Digital 2.0 Mono), English (Dolby Digital 5.1), English (Dolby Digital 2.0 Mono)',
       'English (Dolby Digital 2.0 Mono)',
       'English (DTS-HD Master Audio 5.1), French (DTS-HD 2.0)'],
      dtype=object)

There are only three types of language values which need cleaning, so I will create a function to clean them:

In [30]:
def clean_language(row):
	lang = row.language
	comment = row.comments
	if lang == 'Unqualified, Japanese (Dolby Digital 2.0 Mono), English (Dolby Digital 5.1), English (Dolby Digital 2.0 Mono)' :
		row.language = 'English, Japanese'
		if comment != comment:  #check if comment is NaN
			row.comments = 'Avaliable languages: Japanese (Dolby Digital 2.0 Mono), English (Dolby Digital 5.1), English (Dolby Digital 2.0 Mono)'
		else:
			row.comments += ' Avaliable languages: Japanese (Dolby Digital 2.0 Mono), English (Dolby Digital 5.1), English (Dolby Digital 2.0 Mono)'
	
	elif lang == 'English (Dolby Digital 2.0 Mono)' :
		row.language = 'English'
		if comment != comment:
			row.comments = 'English (Dolby Digital 2.0 Mono)'
		else:
			row.comments += 'English (Dolby Digital 2.0 Mono)'
	
	elif lang == 'English (DTS-HD Master Audio 5.1), French (DTS-HD 2.0)' :
		row.language = 'English, French'
		if comment != comment :
			row.comments = 'English (DTS-HD Master Audio 5.1), French (DTS-HD 2.0)'
		else:
			row.comments += ' English (DTS-HD Master Audio 5.1), French (DTS-HD 2.0)'
	return row

In [31]:
df = df.apply(clean_language, axis=1)

Now the `language` column is clean:

In [32]:
df.language.unique()

array(['English', nan, 'Spanish', 'English, Japanese', 'English, French'],
      dtype=object)

## Clean `publisher`

I want to extract the date of publishing and create a new `publishing_date` column.

In [33]:
df.publisher

0         Notion Press Media Pvt Ltd (November 22, 2021)
1          O'Reilly Media; 1st edition (August 18, 2009)
2      Holy Macro! Books; Third edition (August 1, 2022)
3        O'Reilly Media; 2nd edition (November 14, 2017)
4            For Dummies; 5th edition (February 3, 2022)
                             ...                        
825            Corwin; First edition (December 15, 2017)
826        Springer; 1st ed. 2020 edition (July 2, 2020)
827                      Packt Publishing (July 8, 2022)
828                                                  NaN
829                                                  NaN
Name: publisher, Length: 830, dtype: object

Create a function to extract the publishing date from the values

In [34]:
def extract_date(value):
	if value == value: 
		splited_value = value.split(' (')
		# date is the 2nd value of the list. 
		# Furthermore, drop the closing parenthesis using [:-1]
		if len(splited_value) == 2:
			publisher = splited_value[0]
			date = splited_value[1][:-1]
			return [publisher, date]
		else:
			return 'invalid data'
	else:
		return np.nan

In [35]:
publish_info = df.publisher.apply(extract_date)

In [36]:
publish_info.sample(5)

1      [O'Reilly Media; 1st edition, August 18, 2009]
587    [For Dummies; 1st edition, September 14, 2006]
43                  [Packt Publishing, June 30, 2022]
207        [Apress; 1st ed. edition, January 4, 2023]
93              [Kenneth M Fornari, October 11, 2022]
Name: publisher, dtype: object

I will check if there are any invalid values, in order to investigate them later.

In [37]:
publish_info [publish_info == 'invalid data']

174    invalid data
374    invalid data
586    invalid data
Name: publisher, dtype: object

They are just three values, so there's no need to create a function. I will extract the date manually.

In [38]:
df.loc[374].publisher

'Real Python (realpython.com); 4th edition (August 30, 2022)'

In [39]:
df.loc[374, ['publisher']] = 'Real Python - realpython.com - 4th edition (August 30, 2022)'

<hr style='color: green'/>

In [40]:
df.loc[586].publisher

'Real Python (realpython.com) (May 5, 2021)'

In [41]:
df.loc[586, ['publisher']] = 'Real Python realpython.com (May 5, 2021)'

<hr style='color: green'/>

In [42]:
df.loc[174, ['publisher']]

publisher    ;
Name: 174, dtype: object

In [43]:
df.loc[174, ['publisher']] = np.nan

Once the three anormal data have been processed, I will apply the `extract_date` function again.

In [44]:
publish_info = df.publisher.apply(extract_date)

I create a new column: `publishing_date` :

In [45]:
df['publishing_date'] = [i[1] if (i==i) else i for i in publish_info  ]

In [46]:
df.publishing_date = pd.to_datetime(df.publishing_date)

Now I replace the `publisher` values with the processed publisher information:

In [47]:
df['publisher'] = [i[0] if (i==i) else i for i in publish_info  ]

In [48]:
df.publisher

0            Notion Press Media Pvt Ltd
1           O'Reilly Media; 1st edition
2      Holy Macro! Books; Third edition
3           O'Reilly Media; 2nd edition
4              For Dummies; 5th edition
                     ...               
825               Corwin; First edition
826      Springer; 1st ed. 2020 edition
827                    Packt Publishing
828                                 NaN
829                                 NaN
Name: publisher, Length: 830, dtype: object

In [49]:
df.publisher = df.publisher.str.replace(';', ',')

In [50]:
df.publisher.sample(10)

712                               Packt Publishing
686                           Pearson, 4th edition
574                                No Starch Press
466                                            NaN
787    Dover Publications, 2nd Revised ed. edition
142                               Packt Publishing
356                               Packt Publishing
149                       Brooks Cole, 5th edition
309                         Routledge, 3rd edition
253                                            NaN
Name: publisher, dtype: object

## Clean `ISBN_13`

It seems like some `ISBN_13` values are empty but not set as NaN. Aslo, lenght of ISBN_13 code must be 14 (13 + hyphen).

In [51]:
df.ISBN_13 [ df.ISBN_13.str.len() != 14]

5                              NaN
7      Research in Drama Education
12                             NaN
13                                
14                                
                  ...             
824                             99
825                             59
826                               
828                            NaN
829                               
Name: ISBN_13, Length: 369, dtype: object

In [52]:
df.ISBN_13 [ df.ISBN_13.str.len() != 14].unique()

array([nan, 'Research in Drama Education', ' ', '$13.99 ', '-34%',
       '     ', 'Usually ships within 2 to 3 days.', '#NAME?', '#250 in ',
       '#1 in ', '  Second Edition, Second edition ', '$113.19 ', '-22%',
       'The Data Revolution',
       'Regulating Alcohol around the World: Policy Cocktails', '-19%',
       '#35 in ', 'x', '-27%', '79', '99', '-21%', '75', '49', '69', '29',
       '66', '-30%', '  Kindle Edition ', '$139.99 ', '$13.79 ', 'Python',
       '#372 in ', 'PennyLane', 'JOSH TYSON', '—', '-39%', '59', '39',
       '-25%', '30', '56', '25'], dtype=object)

First set empty values to NaN

In [53]:
df.ISBN_13 = np.where((df.ISBN_13 == '') | (df.ISBN_13 == ' '), np.nan, df.ISBN_13)

Check if row with invalid ISBN_13 values have already comments:

In [54]:
df.ISBN_13 [ df.ISBN_13.str.len() != 14].unique()

array([nan, 'Research in Drama Education', '$13.99 ', '-34%', '     ',
       'Usually ships within 2 to 3 days.', '#NAME?', '#250 in ',
       '#1 in ', '  Second Edition, Second edition ', '$113.19 ', '-22%',
       'The Data Revolution',
       'Regulating Alcohol around the World: Policy Cocktails', '-19%',
       '#35 in ', 'x', '-27%', '79', '99', '-21%', '75', '49', '69', '29',
       '66', '-30%', '  Kindle Edition ', '$139.99 ', '$13.79 ', 'Python',
       '#372 in ', 'PennyLane', 'JOSH TYSON', '—', '-39%', '59', '39',
       '-25%', '30', '56', '25'], dtype=object)

In [55]:
invalid_isbn_values = list(df.ISBN_13 [ df.ISBN_13.str.len() != 14].unique())

In [56]:
invalid_isbn_values[:5]

[nan, 'Research in Drama Education', '$13.99 ', '-34%', '     ']

Let's drop the nan values from invalid isbn values:

In [57]:
invalid_isbn_values = invalid_isbn_values[1:]

Let's check if the rows with prices in the `ISBN_13` column have the price set.

In [58]:
df[['price', 'ISBN_13']][df.ISBN_13.isin(invalid_isbn_values)].T

7        31     61      80   \
price                           90.0    13.99  26.49  121.99   
ISBN_13  Research in Drama Education  $13.99    -34%           

                                       91      121       134     138  \
price                                 31.3   26.44       NaN     NaN   
ISBN_13  Usually ships within 2 to 3 days.  #NAME?  #250 in   #1 in    

                                       161       195  ...    725    730  \
price                                24.95    113.19  ...  14.19  41.16   
ISBN_13    Second Edition, Second edition   $113.19   ...     39   -25%   

           731   732     763    787   796    819   824   825  
price    14.99  15.3  139.56  11.89  46.5  24.95  9.69  5.33  
ISBN_13     99    30      56     69  -22%     25    99    59  

[2 rows x 56 columns]

At the sight of the results, besides a couple of rows,the rest of the ISBN invalid values are not worth processing. I will just set them as NaN.  
I will process the rows number: 7, 161, 233 and 292

In [59]:
df.loc[[7,161,233,292], ['title', 'ISBN_13', 'comments'] ]

title  \
7      Qualitative Data Analysis: A Methods Sourcebook   
161  Guerrilla Data Analysis Using Microsoft Excel:...   
233  The Data Revolution: A Critical Analysis of Bi...   
292  An Introduction to Data Analysis: Quantitative...   

                                               ISBN_13 comments  
7                          Research in Drama Education      NaN  
161                    Second Edition, Second edition       NaN  
233                                The Data Revolution      NaN  
292  Regulating Alcohol around the World: Policy Co...      NaN

It seems like book in row 292 has an ISBN value that has nothing to do this its title.

In [60]:
df.loc[292, ['title']].values

array(['An Introduction to Data Analysis: Quantitative, Qualitative and Mixed Methods'],
      dtype=object)

In [61]:
df.loc[292, 'ISBN_13']

'Regulating Alcohol around the World: Policy Cocktails'

I will clean manually these 4 rows:

In [62]:
df.loc[7, 'comments'] = 'Research in Drama Education'
df.loc[161, 'ISBN_13'] = 'Second edition'
df.loc[[233, 292], 'ISBN_13'] = np.nan

The rest of invalid ISBN values will be set to NaN

In [63]:
df[['price', 'ISBN_13']][df.ISBN_13.isin(invalid_isbn_values)].T

7        31     61      80   \
price                           90.0    13.99  26.49  121.99   
ISBN_13  Research in Drama Education  $13.99    -34%           

                                       91      121       134     138  \
price                                 31.3   26.44       NaN     NaN   
ISBN_13  Usually ships within 2 to 3 days.  #NAME?  #250 in   #1 in    

              195    217  ...    725    730    731   732     763    787   796  \
price      113.19  46.53  ...  14.19  41.16  14.99  15.3  139.56  11.89  46.5   
ISBN_13  $113.19    -22%  ...     39   -25%     99    30      56     69  -22%   

           819   824   825  
price    24.95  9.69  5.33  
ISBN_13     25    99    59  

[2 rows x 53 columns]

In [64]:
df.loc[df.ISBN_13.isin(invalid_isbn_values), 'ISBN_13'] = np.nan

I check ISBN values again...

In [65]:
[i for i in df['ISBN_13'].dropna().unique() if not i.startswith('9')]

['Second edition', 'Pratip Samanta']

A couple of rows still need a cleaning

In [66]:
invalid_isbn_values = [i for i in df['ISBN_13'].dropna().unique() if not i.startswith('9')]

In [67]:
df[['ISBN_13', 'comments']][df.ISBN_13.isin(invalid_isbn_values)]

ISBN_13 comments
161  Second edition      NaN
427  Pratip Samanta      NaN

In [68]:
df.loc[[161, 427], 'comments'] = df.loc[[161, 427], 'ISBN_13']
df.loc[[161, 427], 'ISBN_13'] = np.nan

Finally ISBN column is clean:

In [69]:
[i for i in df['ISBN_13'].dropna().unique() if not i.startswith('9')]

[]

In [70]:
df.ISBN_13.sample(15)

606    979-8364281784
752    978-0525509202
322               NaN
358               NaN
117               NaN
36     978-1718502208
669               NaN
708    978-0198862758
827    978-1803241333
424               NaN
9      978-1617296055
778    978-0984782857
666               NaN
277    978-1473756540
783               NaN
Name: ISBN_13, dtype: object

## Fine tuning of titles

In [71]:

def lower_words(title_string):
    words_to_lower = ['Using', 'And', 'For']
    for word in words_to_lower:
        if word in title_string:
            title_string = title_string.replace(word, word.lower())
    return title_string

In [72]:
df.title = df.title.apply(lower_words)

## Reorder dataset

A final reorder of the columns in the dataset.

In [73]:
new_order = ['title', 'author', 'publisher', 'publishing_date', 'pages', 'price', 'language', 'ISBN_13', 'complete_link', 'comments']

In [74]:
df = df.reindex(new_order, axis=1)

Finally, get a sample to have an overview of the clean dataset.

In [75]:
df.sample(10)

title  \
605  Continuous Delivery with Docker and Jenkins: C...   
711  Data Science Crash Course for Beginners with P...   
707  Data Quality Fundamentals: A Practitioner's Gu...   
786       Introduction to Probability for Data Science   
121  Doing Data Science: Straight Talk from the Fro...   
347  Mastering PyTorch: Build powerful neural netwo...   
823                        Foundations of Data Science   
670  Text as Data: A New Framework for Machine Lear...   
464  Practical Python Programming for IoT: Build ad...   
32    Python for Everybody: Exploring Data in Python 3   

                                          author  \
605                                 Rafal Leszko   
711                                          NaN   
707              Barr Moses, Lior Gavish, et al.   
786                                 Stanley Chan   
121              "Cathy ONeil" and Rachel Schutt   
347    Ashish Ranjan Jha and Dr. Gopinath Pillai   
823            Avrim Blum, John Hopcroft, et al.   
670  Justin Grimmer, Margaret E. Roberts, et al.   
464                                   Gary Smart   
32   Charles R. Severance, Aimee Andrion, et al.   

                         publisher publishing_date  pages  price language  \
605  Packt Publishing, 2nd edition      2019-05-31  350.0  46.99  English   
711              AI Publishing LLC      2020-08-31  314.0  23.48  English   
707    O'Reilly Media, 1st edition      2022-10-11  308.0  46.99  English   
786   Michigan Publishing Services      2021-11-05  704.0  70.00  English   
121    O'Reilly Media, 1st edition      2013-11-19  408.0  26.44  English   
347               Packt Publishing      2021-02-12  450.0  39.99  English   
823                            NaN             NaT    NaN  51.99      NaN   
670     Princeton University Press      2022-03-29  360.0  35.99  English   
464               Packt Publishing      2020-11-12  516.0  39.99  English   
32                             NaN             NaT  387.0   0.99  English   

            ISBN_13                                      complete_link  \
605  978-1838552183  https://www.amazon.com/gp/slredirect/picassoRe...   
711  978-1734790146  https://www.amazon.com/Science-Crash-Course-Be...   
707             NaN  https://www.amazon.com/Data-Quality-Fundamenta...   
786  978-1607857464  https://www.amazon.com/Introduction-Probabilit...   
121             NaN  https://www.amazon.com/Doing-Data-Science-Stra...   
347             NaN  https://www.amazon.com/gp/slredirect/picassoRe...   
823             NaN  https://www.amazon.com/Foundations-Data-Scienc...   
670             NaN  https://www.amazon.com/Text-Data-Framework-Lea...   
464             NaN  https://www.amazon.com/gp/slredirect/picassoRe...   
32              NaN  https://www.amazon.com/Python-Everybody-Explor...   

    comments  
605      NaN  
711      NaN  
707      NaN  
786      NaN  
121      NaN  
347      NaN  
823      NaN  
670      NaN  
464      NaN  
32       NaN

## Export the result

In [76]:
df.to_csv('data_science_books_clean.csv', index=False, na_rep='NaN')